# vis.mac for rdecay02, as modified by AB and RF 2021
#
# Sets some default verbose
# and initializes the graphic.
#
/control/verbose 2
/run/verbose 2
# ADDED BY RYAN: Define geometry before /run/initialize
# DEFINE GEOMETRY PRIOR TO "/run/initialize"
# /rdecay02/det/setTargetThickness 1000 um # thickness
 #/rdecay02/det/setTargetLength 10 um
 #/rdecay02/det/setDetectorThickness 20 um
 #/rdecay02/det/setDetectorSide 40 um
 
 
/run/initialize
#
# Use this open statement to create an OpenGL view:
/vis/open OGL 600x600-0+0
#
# Use this open statement to create a .prim file suitable for
# viewing in DAWN:
#/vis/open DAWNFILE
#
# Use this open statement to create a .heprep file suitable for
# viewing in HepRApp:
#/vis/open HepRepFile
#
# Use this open statement to create a .wrl file suitable for
# viewing in a VRML viewer:
#/vis/open VRML2FILE
#
# Disable auto refresh and quieten vis messages whilst scene and
# trajectories are established:
/vis/viewer/set/autoRefresh false
/vis/verbose errors
#
# Draw geometry:
/vis/drawVolume
#
# Specify view angle:
#/vis/viewer/set/viewpointThetaPhi 90 0.
/vis/viewer/set/viewpointVector 1 0 0
#/vis/viewer/set/lightsVector -1 0 0
#
# Specify zoom value:
/vis/viewer/zoomTo 32
#
# Specify style (surface (s) or wireframe (w)):
/vis/viewer/set/style w
# To get nice view
# /vis/geometry/set/visibility World 0 false
#
# Draw coordinate axes:
#/vis/scene/add/axes 0 0 0 .05 mm

# SET COLOR OF OBJECTS
# forceWireframe forceSolid

/vis/geometry/set/forceWireframe World 1
/vis/geometry/set/forceSolid Detector 1
/vis/geometry/set/forceSolid Target 1
/vis/geometry/set/colour World 0 1 0 0 1  # depth R G B Opacity
/vis/geometry/set/colour Detector 0 0 1 1 1  # depth R G B Opacity
/vis/geometry/set/colour Target 0 1 1 .1 1   # depth R G B Opacity



#
# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts false
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 1
# (if too many tracks cause core dump => /tracking/storeTrajectory 0)
#
# Draw hits at end of event:
#/vis/scene/add/hits
#
# To draw only gammas:
#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add gamma
#
# To invert the above, drawing all particles except gammas,
# keep the above two lines but also add:
#/vis/filtering/trajectories/particleFilter-0/invert true
#
# Many other options are available with /vis/modeling and /vis/filtering.
# For example, to select colour by particle ID:
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set e- red
/vis/modeling/trajectories/drawByParticleID-0/set gamma green
/vis/modeling/trajectories/drawByParticleID-0/set neutron yellow
/vis/modeling/trajectories/drawByParticleID-0/set alpha blue
/vis/modeling/trajectories/drawByParticleID-0/set GenericIon blue
#
# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate -1
#
# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose warnings
#
# For file-based drivers, use this to create an empty detector view:
#/vis/viewer/flush

# ADDED BY RYAN
# place the isotopes in the middle of the target, at rest. 
/gun/particle ion
#/gun/ion 95 241 # Am-241
/gun/ion 94 238 # Pu-238
/gun/energy 0 MeV

#/gun/particle alpha
#/gun/energy 5.51 MeV

/process/had/rdm/nucleusLimits 238 238 94 94
#
# Need to set file name and energy window.
# /analysis/setFileName Am241
# Need to set at least one hist to avoid seg fault (why?)
 /analysis/h1/set 0 10 5. 6. MeV

#
/process/had/rdm/applyICM true
/process/had/rdm/applyARM true
/process/had/rdm/hlThreshold 1 s

/run/beamOn 100